expense_manager/add_expense/urls.py
from django.conf.urls import url

from .views import date_find
from . import views

app_name = 'add_expense'

urlpatterns = [
    url(r'^add_expense/', views.add_expense, name='add_expense'),
    url(r'^view_expense/', views.view_expense, name='view_expense'),
    url(r'^get_expense/(?P<pk>\d+)/', views.get_expense, name='get_expense'),
    url(r'^edit_expense/(?P<pk>\d+)/', views.edit_expense, name='edit_expense'),
    url(r'^date_find/', views.date_find, name='date_find'),
    url(r'^date_find_2/', views.date_find_2, name='date_find_2'),

]

expense_manager/expense_manager/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from build import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^special/', views.special,name='special'),
    url(r'^admin/', admin.site.urls),
    url(r'^build_app/', include('build.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^expense/', include('add_expense.urls', namespace="expense")),
]

expense_manager/add_expense/models.py
from __future__ import unicode_literals

from django.contrib import auth
from django.db import models

from django.core.validators import MaxValueValidator, RegexValidator


class Payments(models.Model):

        paymen = models.CharField(max_length=30, blank=True, null=True)

        def __str__(self):
            return self.paymen

class Expenses(models.Model):

        expen = models.CharField(max_length=30, blank=True, null=True)

        def __str__(self):
            return self.expen


class AddExpense(models.Model):
    expense_title = models.CharField('Expense Title', max_length=20)
    amount = models.DecimalField('Amount', decimal_places=2, max_digits=10)
    currency = models.CharField('Currency', max_length=23)
    vendor_name = models.CharField('Vendor Name', max_length=200, blank=True)
    last4digit = models.CharField(max_length=4, validators=[RegexValidator(r'^\d{1,4}$')])
    invoice = models.IntegerField()
    userid = models.IntegerField()
    date = models.DateField()
    payment_type = models.ForeignKey(Payments)
    expense_type = models.ForeignKey(Expenses)

expense_manager/add_expense/forms.py
from django import forms

from add_expense.models import AddExpense

class AddExpenseForm(forms.ModelForm):

    class Meta:
        model = AddExpense
        fields = '__all__'

expense_manager/add_expense/views.py
import user
from datetime import timedelta, date

from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from add_expense.forms import AddExpenseForm
from add_expense.models import AddExpense

@login_required
def add_expense(request):
    expense_added = False
    if request.method == 'POST':

        add_expense_form = AddExpenseForm(data=request.POST)
        if add_expense_form.is_valid():
            add_expense_form.save()
        expense_added = True
    else:
        add_expense_form = AddExpenseForm()

    return render(request, 'based/add_expense.html', {'add_expense_form': add_expense_form, 'expense_added': expense_added})

@login_required
def view_expense(request):
    expenses = AddExpense.objects.all()

    return render(request, 'based/view_expense.html', {'expenses': expenses})

@login_required
def get_expense(request, pk):
    expense = AddExpense.objects.get(id=pk)
    add_expense_form = AddExpenseForm(instance=expense)
    if add_expense_form.is_valid():
        print add_expense_form
    else:
        print 'Invalid'
    return render(request, 'based/edit_expense.html', {'add_expense_form': add_expense_form})

@login_required
def edit_expense(request, pk):
    expense = AddExpense.objects.get(id=pk)
    form = AddExpenseForm(request.POST, instance=expense)
    if form.is_valid():
        form.save()
    return render(request, 'based/edit_expense.html', {'editing': True})

@login_required
def date_find(request):
    samples = AddExpense.objects.filter(date__year='2018',
                          date__month='5')

    return render(request, 'based/date_change.html', {'samples': samples})



@login_required
def date_find_2(request):
    samples = AddExpense.objects.filter(date__range=["2018-05-14", "2018-06-27"])

    return render(request, 'based/date_find_2.html', {'samples': samples})

expense_manager/add_expense/templates/based/add_expense.html
{% extends "basic_app/base.html" %}


{% block body_block %}

  <div class="container">
    <div class="jumbotron">
      {% if expense_added %}<hr>
        <h1>Expense Added</h1><hr>
      {% else %}
        <h1>Add the expense</h1>
      <hr>

        <form method="POST"><hr>
          {% csrf_token %}<hr>
          <ul>{{ add_expense_form.as_ul }}</ul><hr>
          <input type="submit" value="Add Expense">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

expense_manager/add_expense/templates/based/based.html
<!DOCTYPE html>
<html lang="en">
<head>
       <title>Title</title>
    <meta charset="UTF-8">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<style>

table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 6px;
}

th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 1px;
    background-color: #6a5aef;

}
tr:nth-child(even) {
    background-color: #dddddd;

}
</style>
</head>
<body>
 <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'build:register' %}">Register</a></li>

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li><a href="{% url 'add_expense:view_expense' %}">View Expenses</a></li>
            <li><a href="{% url 'build:password' %}">Change Password</a></li>
            <li><a href="{% url 'add_expense:add_expense' %}">Add Expense<E></E>Expense</a></li>

          {% else %}
            <li><a class="navbar-link" href="{% url 'build:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
{% block body_block %}

{% endblock %}

</body>
</html>

expense_manager/add_expense/templates/based/date_change.html
{% extends "based/based.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <table>

            {% for expense in samples %}
            <th>
                <th><td>{{ expense.expense_title }}</td></th>
                <th><td>{{ expense.amount }}</td></th>
                <th><td>{{ expense.currency }}</td></th>
                <th><td>{{ expense.payment_type }}</td></th>
                <th><td>{{ expense.expense_type }}</td></th>
                <th><td>{{ expense.vendor_name }}</td></th>
                <th><td>{{ expense.last4digit }}</td></th>
                <th><td>{{ expense.invoice }}</td></th>
                <th><td>{{ expense.userid }}</td></th>
                    <td><a href={% url 'expense:get_expense' pk=expense.id %}><button type="submit">Edit</button></a></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No expenses</td>
            </tr>
            {% endfor %}
        </table>
    </div>
  </div>
{% endblock %}

expense_manager/add_expense/templates/based/date_find_2.html
{% extends "based/based.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <table>

            {% for expense in samples %}
            <tr>
                <td>{{ expense.expense_title }}</td>
                <td>{{ expense.amount }}</td>
                <td>{{ expense.currency }}</td>
                <td>{{ expense.payment_type }}</td>
                <td>{{ expense.expense_type }}</td>
                <td>{{ expense.vendor_name }}</td>
                <td>{{ expense.last4digit }}</td>
                <td>{{ expense.invoice }}</td>
                <td>{{ expense.userid }}</td>
                    <td><a href={% url 'expense:get_expense' pk=expense.id %}><button type="submit">Edit</button></a></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No expenses</td>
            </tr>
            {% endfor %}
        </table>
    </div>
  </div>
{% endblock %}

expense_manager/add_expense/templates/based/edit_expense.html
{% extends "based/based.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if editing %}
        <h1>Expense Updated</h1>
      {% else %}
        <h1>Edit the expense</h1>
        <form action="/expense/edit_expense/{{ add_expense_form.instance.id }}/" method="POST">
          {% csrf_token %}
          {{ add_expense_form.as_p }}
          <input type="submit" value="update">
        </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

expense_manager/add_expense/templates/based/expense.html
{% extends "based/based.html" %}
{% load staticfiles %}

{% block body_block %}

  {% if home%}
    <ol>
        <li>User Info</li>
        <form ="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_exp.as_p }}
          <input type="submit" name="" value="Register">
        </form>


    </ol>
  {% endif %}

{% endblock %}

expense_manager/add_expense/templates/based/view_expense.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <table>
            <tr>
                <td>Expense Title</td>
                <td>Amount</td>
                <td>Currency</td>
                <td>Payment Type</td>
                <td>Expense Type</td>
                <td>Vendor Name</td>
                <td>Last 4 Digits</td>
                <td>Invoice</td>
                <td>User Id</td>

                <td>Edit</td>
            </tr>
            {% for expense in expenses %}
            <tr>
                <td>{{ expense.expense_title }}</td>
                <td>{{ expense.amount }}</td>
                <td>{{ expense.currency }}</td>
                <td>{{ expense.payment_type }}</td>
                <td>{{ expense.expense_type }}</td>
                <td>{{ expense.vendor_name }}</td>
                <td>{{ expense.last4digit }}</td>
                <td>{{ expense.invoice }}</td>
                <td>{{ expense.userid }}</td>
                    <td><a href={% url 'expense:get_expense' pk=expense.id %}><button type="submit">Edit</button></a></td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No expenses</td>
            </tr>
            {% endfor %}
        </table>
    </div>
  </div>
{% endblock %}

expense_manager/templates/basic_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link / Admin Link / Register Link#}
          <li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'build:register' %}">Register</a></li>

          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li><a href="{% url 'add_expense:view_expense' %}">View Expenses</a></li>
            <li><a href="{% url 'build:password' %}">Password</a></li>
            <li><a href="{% url 'add_expense:add_expense' %}">Add <E></E>Expense</a></li>

          {% else %}
            <li><a class="navbar-link" href="{% url 'build:user_login' %}">Login</a></li>
          {% endif %}
          
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>


  </body>
</html>

expense_manager/templates/basic_app/change_password.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}


{% block body_block %}

    <form method="post">
  {% csrf_token %}
  {{ form.as_table }}
  <button type="submit">Save changes</button>
</form>
{% endblock %}

expense_manager/templates/basic_app/date.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ changes }}
</body>
</html>

expense_manager/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>Infinodo</h1>
    {% if user.is_authenticated %}
        <h2>Welcome {{ user.username }}!</h2>
    {% else %}
        <h2>Welcome to the site!</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

expense_manager/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'build:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

expense_manager/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>

{% endblock %}